spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot
    username: tuser
    password: tjee1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      idle-timeout: 600000
      pool-name: MyHikariCP
      auto-commit: false


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.my.gamebackend
  config-location: classpath:/mybatis-config.xml

log:
  config:
    path: ./logs/
    fileName: application