name: game_workspace
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  dio: ^5.4.3
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  web: ^1.1.1
  webview_flutter: ^4.4.4
  google_fonts: ^7.0.2
  go_router: ^17.0.1
  image_picker: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bird_fluffy/
    - assets/images/dress_up/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf